version: 0.2

phases:
  install:
    commands:
      #- sudo yum install python3
      - sudo yum install python34 python34-pip
      - python3 test_zap.py
  build:
    commands:
      - python3 test_zap.py
artifacts:
  files:
    - '**/*'
